### PR TITLE
Update cmake to pass along console_bridge

### PR DESCRIPTION
**Pull request by wjwwood**
It was not passing along rosconsole or console_bridge correctly.

It was find_package'ing after catkin_package.

It was not treating console_bridge like a catkin dependency.

### CODE REVIEW

**Comment by wjwwood** [comment]
@dirk-thomas Fixed the style things, but @isucan already released it, so I pushed it to master, it will get into the next release.

**Comment by isucan** [comment]
@wjwwood  the commit does not seem to change much: 6398a4b6673d642118c96845562b1df498556c80
I tried to fix what @dirk-thomas said as well :) Do we need a re-release?

**Comment by wjwwood** [comment]
http://ros.org/doc/groovy/api/catkin/html/user_guide/package.html

I would think that we can just leave it till the next release, but that is
up to @dirk-thomas

On Wed, Dec 5, 2012 at 10:18 AM, isucan notifications@github.com wrote:

> @wjwwood https://github.com/wjwwood the commit does not seem to change
> much: 6398a4bhttps://github.com/ros/rosconsole_bridge/commit/6398a4b6673d642118c96845562b1df498556c80
> I tried to fix what @dirk-thomas https://github.com/dirk-thomas said as
> well :) Do we need a re-release?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ros/rosconsole_bridge/pull/1#issuecomment-11053455.

## 

William Woodall
Willow Garage - Software Engineer
wwoodall@willowgarage.com

**Comment by dirk-thomas** [comment]
Sure, just style - it fine if it is just committed - does not need to be released.

**Pull request merged**
