### PR TITLE
Fix use of deprecated logging functions.

### PR DESCRIPTION
**Pull request by mikepurvis**
See: https://github.com/ros/console_bridge/blob/master/include/console_bridge/console.h#L68-L90

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Indigo does not have the necessary version of `console_bridge` for this. Maybe this should be branched for Kinetic?

**Comment by dirk-thomas** [comment]
@mikepurvis How do you want to proceed on this?

**Comment by mikepurvis** [comment]
It doesn't really matter to me. I just periodically try to clean some of the low-hanging fruit as far as warnings in our builds. If you guys want to fork for Kinetic+, that's reasonable, or I can put up a PR that does undef tricks suggested by @mikaelarguedas.

**Comment by dirk-thomas** [comment]
Since this repo has a very low rate of changes I am fine with branching. I created a `kinetic-devel` branch and updated the release repo (https://github.com/ros-gbp/rosconsole_bridge-release/commit/05ba076126b2b37b5bcf48786ae2b63aa3a6095c).

**Comment by dirk-thomas** [comment]
I retargeted the new branch. Thank you for fixing the warnings.

**Comment by dirk-thomas** [comment]
For the record: ros/rosdistro#16146

**Pull request merged**
