### PR TITLE
rename variables within rosconsole macros

### PR DESCRIPTION
**Pull request by dirk-thomas**
Renames according to ros/ros_comm#443

### CODE REVIEW

**Comment by wjwwood** [comment]
+1 for indigo and not hydro, don't forget to update the migration guide.

**Comment by dirk-thomas** [comment]
Good point - done: http://wiki.ros.org/action/diff/indigo/Migration?action=diff&rev1=13&rev2=14

**Comment by isucan** [comment]
Should we branch for indigo first?

**Comment by dirk-thomas** [comment]
Indeed :wink: I will manually merge this to the just created _indigo-devel_ branch. Also updated the distro file accordingly: https://github.com/ros/rosdistro/commit/bcd90f389a758c19ffddd96693ce8d8e01834777#diff-4bbb8e35ff5dc5e7f2d7b4d00374533f

**Comment by dirk-thomas** [comment]
Merged: 4984dc6a81dfa0a54005c76bc33e206c4dbe48ff

**Pull request closed without merging**
